#!/bin/bash
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.

echo "commit-msg hook"

COMMENT=`cat "$1"`
#BRANCH=`git symbolic-ref --short HEAD`
BRANCH=`git rev-parse --abbrev-ref HEAD`
FIRST_COMMENT_CHAR=${COMMENT:0:1}

if [ "$FIRST_COMMENT_CHAR" = "<" ]; then
  exit
fi


COMMENT="<$BRANCH> $COMMENT"
echo "$COMMENT" > "$1"


echo "commit-msg hook completed"
